-- Resposta do Comando SQL 
--item a)
--Cadastro Clientes
INSERT INTO MC_CLIENTE (
    NM_CLIENTE,
    QT_ESTRELAS,
    VL_MEDIO_COMPRA,
    ST_CLIENTE,
    DS_EMAIL,
    NR_TELEFONE,
    NM_LOGIN,
    DS_SENHA)
VALUES ('CLIENTE PESSOA FISICA', 3, 0, 'A', 'CLIENTEFISICA@GMAIL.COM', '(011)99855-6598', 'CLIENTEFISICA', '123456'); 
COMMIT; 

INSERT INTO MC_CLIENTE (
    NM_CLIENTE,
    QT_ESTRELAS,
    VL_MEDIO_COMPRA,
    ST_CLIENTE,
    DS_EMAIL,
    NR_TELEFONE,
    NM_LOGIN,
    DS_SENHA)
VALUES ('CLIENTE PESSOA JURIDICA', 2, 0, 'A', 'CLIENTEJURIDICA@GMAIL.COM', '(011)99844-6878', 'CLIENTEJURIDICA', '123456'); 
COMMIT;

--Cadastro Cliente Pessoa Fisica
INSERT INTO MC_CLI_FISICA (
    NR_CLIENTE,
    DT_NASCIMENTO,
    FL_SEXO_BIOLOGICO,
    DS_GENERO,
    NR_CPF) 
VALUES(8, TO_DATE('23/11/1980','DD/MM/YYYY'), 'F', 'FEMININO',44271349801);
COMMIT;


--Cadastro Cliente Pessoa Juridica
INSERT INTO MC_CLI_JURIDICA (
    NR_CLIENTE, 
    DT_FUNDACAO,
    NR_CNPJ,
    NR_INSCR_EST)
VALUES (9,TO_DATE('01/02/2020','DD/MM/YYYY'),  '590001980545','68885487');
COMMIT;

--Cadastro endereço Cliente Pessoa Fisica
INSERT INTO MC_END_CLI (
    NR_CLIENTE, 
    CD_LOGRADOURO_CLI, 
    NR_END,
    DS_COMPLEMENTO_END, 
    DT_INICIO, 
    DT_TERMINO, 
    ST_END)
VALUES (8, 3, 710, null, to_date ('01/01/2025', 'dd/mm/yyyy'), null, 'A'); 
COMMIT; 

--Cadastro endereço Cliente Pessoa Juridica
INSERT INTO MC_END_CLI (
    NR_CLIENTE, 
    CD_LOGRADOURO_CLI, 
    NR_END,
    DS_COMPLEMENTO_END, 
    DT_INICIO, 
    DT_TERMINO, 
    ST_END)
VALUES (11, 5, 516, null, to_date ('01/02/2025', 'dd/mm/yyyy'), null, 'A'); 
COMMIT; 

--Item b)
--Cadastro Clientes
INSERT INTO MC_CLIENTE (
    NM_CLIENTE,
    QT_ESTRELAS,
    VL_MEDIO_COMPRA,
    ST_CLIENTE,
    DS_EMAIL,
    NR_TELEFONE,
    NM_LOGIN,
    DS_SENHA)
VALUES ('CLIENTE LOGIN EXISTENTE', 4, 0, 'A', 'CLIENTELOGINEXISTENTE@GMAIL.COM', '(011)99855-6598', 'CLIENTEFISICA', '123456'); 

-- Item c)
SELECT * FROM MC_FUNCIONARIO WHERE CD_FUNCIONARIO = 7; 

UPDATE MC_FUNCIONARIO 
SET DS_CARGO = 'Superintendente', 
    VL_SALARIO = VL_SALARIO * 1.12
WHERE CD_FUNCIONARIO = 7; 

--Item d)
SELECT * FROM MC_END_CLI WHERE NR_CLIENTE = 11; 

UPDATE MC_END_CLI
SET ST_END = 'I', 
    DT_TERMINO = TO_DATE ('22/04/2025', 'DD/MM/YYYY')
WHERE  NR_CLIENTE = 11;
COMMIT;     

--Item e) 
DELETE FROM MC_ESTADO 
WHERE SG_ESTADO = 'SP'; 

--Item f)
SELECT * FROM MC_PRODUTO WHERE CD_PRODUTO = 3; 

UPDATE MC_PRODUTO 
SET ST_PRODUTO = 'X'
WHERE CD_PRODUTO = 3; 






